package com.ssm.mapper;

import com.ssm.model.Information;
import com.ssm.model.dto.TitleDto;

import java.util.List;

public interface InformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inforid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insert(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insertSelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    Information selectByPrimaryKey(Integer inforid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Information record);
    List<TitleDto> titlelist(int id);
    List<TitleDto> titlelist1(int id);
    int countStuTitle(int id);
    int countAdmTitle(int id);
    List<Information> SingUpTitle(int id);
    List<Information> CollectTitle(int id);
    List<Information> draft(int id);
    List<Information> recycle(int id);
    Information peoplenum(int id);
    int updatepeoplenum(Information information);
    int fabu(int id);
    int delete(int id);
    int huifu(int id);
    List<Information> studentinfor();
}