package com.ssm.mapper;

import com.ssm.model.Queryschool;

import java.util.List;

public interface QueryschoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queryschool
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queryschool
     *
     * @mbggenerated
     */
    int insert(List<Queryschool> queryschools);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queryschool
     *
     * @mbggenerated
     */
    int insertSelective(Queryschool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queryschool
     *
     * @mbggenerated
     */
    Queryschool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queryschool
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Queryschool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queryschool
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Queryschool record);
}