package com.ssm.mapper;

import com.ssm.model.SignUp;
import org.apache.ibatis.annotations.Param;

public interface SignUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbggenerated
     */
    int insert(SignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbggenerated
     */
    int insertSignSelective(SignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbggenerated
     */
    SignUp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SignUp record);

//查询有没有报名
    SignUp issignselect(SignUp signUp);

    //
    int upadteById(@Param("idsc")String[] idsc);

    int upadteByInforid(int inforid);
}