package com.ssm.model;

import java.io.Serializable;

public class SignUp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.inforid
     *
     * @mbggenerated
     */
    private Integer inforid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.studentid
     *
     * @mbggenerated
     */
    private Integer studentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.id
     *
     * @return the value of sign_up.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.id
     *
     * @param id the value for sign_up.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.inforid
     *
     * @return the value of sign_up.inforid
     *
     * @mbggenerated
     */
    public Integer getInforid() {
        return inforid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.inforid
     *
     * @param inforid the value for sign_up.inforid
     *
     * @mbggenerated
     */
    public void setInforid(Integer inforid) {
        this.inforid = inforid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.studentid
     *
     * @return the value of sign_up.studentid
     *
     * @mbggenerated
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.studentid
     *
     * @param studentid the value for sign_up.studentid
     *
     * @mbggenerated
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }
}